# .github/workflows/azure-static-web-apps-black-sea-0e7490b10.yml
name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event.action != 'closed' && github.event_name == 'pull_request')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Install OIDC Client from Core Package
        run: npm install @actions/core@1.6.0 @actions/http-client

      - name: Get Id Token
        uses: actions/github-script@v6
        id: idtoken
        with:
          script: |
            const coredemo = require('@actions/core')
            return await coredemo.getIDToken()
          result-encoding: string

      - name: Build Frontend (Vite)
        run: |
          npm install
          echo "Debug: VITE_API_BASE_URL en build step (parcial): ${VITE_API_BASE_URL:0:10}..."
          VITE_API_BASE_URL="${{ secrets.VITE_API_BASE_URL }}" npm run build
        working-directory: ./
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}

      # --- ¡NUEVO PASO: SUBIR ARTEFACTOS DEL BUILD! ---
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4 # Usa la acción de subir artefactos
        with:
          name: frontend-build-output # Nombre del artefacto que podrás descargar
          path: dist/public # La ruta de la carpeta que queremos subir
          # optional: retention-days: 5 # Cuántos días guardar el artefacto, opcional

      - name: Deploy to Azure Static Web Apps
        id: deploy_swa
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_SEA_0E7490B10 }}
          action: "upload"
          app_location: "/"
          api_location: ""
          output_location: "dist/public"
          github_id_token: ${{ steps.idtoken.outputs.result }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "close"